"""added one_attempt_only boolean to quiz

Revision ID: 4fbbe9528ee7
Revises: 9b7eb8f7b946
Create Date: 2025-02-03 17:51:12.196552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fbbe9528ee7'
down_revision = '9b7eb8f7b946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('one_attempt_only', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('one_attempt_only')

    # ### end Alembic commands ###
