"""Initial migration.

Revision ID: 862b559688ae
Revises: 
Create Date: 2025-01-02 14:54:48.370889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862b559688ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
