"""added weight to questions

Revision ID: af8367f821df
Revises: 862b559688ae
Create Date: 2025-01-06 15:35:37.468943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af8367f821df'
down_revision = '862b559688ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=False))

    with op.batch_alter_table('quiz_results', schema=None) as batch_op:
        batch_op.alter_column('marks_scored',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('total_marks',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_results', schema=None) as batch_op:
        batch_op.alter_column('total_marks',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('marks_scored',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
