"""changes in payment history

Revision ID: df18795a2806
Revises: 
Create Date: 2025-01-14 10:07:37.805536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df18795a2806'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=100), nullable=False))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('order_id')
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('order_id', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###
